"""empty message

Revision ID: 1081b1ee7f52
Revises: 
Create Date: 2025-11-18 22:57:30.254092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1081b1ee7f52'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('value_type', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_setting', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_setting_key'), ['key'], unique=True)

    op.create_table('calculation_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=128), nullable=False),
    sa.Column('report_period', sa.String(length=64), nullable=True),
    sa.Column('upload_timestamp', sa.DateTime(), nullable=True),
    sa.Column('detailed_results_json', sa.Text(), nullable=True),
    sa.Column('targets_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    with op.batch_alter_table('calculation_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calculation_run_report_period'), ['report_period'], unique=False)
        batch_op.create_index(batch_op.f('ix_calculation_run_upload_timestamp'), ['upload_timestamp'], unique=False)

    op.create_table('commission_rule_set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('min_sales', sa.Float(), nullable=False),
    sa.Column('max_sales', sa.Float(), nullable=False),
    sa.Column('marketer_rate', sa.Float(), nullable=True),
    sa.Column('negotiator_rate', sa.Float(), nullable=True),
    sa.Column('coordinator_rate', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('commission_rule_set', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_commission_rule_set_model_name'), ['model_name'], unique=False)

    op.create_table('monthly_target',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('collective_target', sa.Float(), nullable=True),
    sa.Column('individual_target', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'month', name='_year_month_uc')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('person_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_name', sa.String(length=128), nullable=False),
    sa.Column('commission_model', sa.String(length=64), nullable=True),
    sa.Column('total_original_commission', sa.Float(), nullable=True),
    sa.Column('total_additional_bonus', sa.Float(), nullable=True),
    sa.Column('total_payable_commission', sa.Float(), nullable=True),
    sa.Column('total_paid_commission', sa.Float(), nullable=True),
    sa.Column('remaining_balance', sa.Float(), nullable=True),
    sa.Column('total_full_commission', sa.Float(), nullable=True),
    sa.Column('total_pending_commission', sa.Float(), nullable=True),
    sa.Column('calculation_run_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['calculation_run_id'], ['calculation_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('person_result', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_person_result_person_name'), ['person_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person_result', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_person_result_person_name'))

    op.drop_table('person_result')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_name'))

    op.drop_table('user')
    op.drop_table('monthly_target')
    with op.batch_alter_table('commission_rule_set', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commission_rule_set_model_name'))

    op.drop_table('commission_rule_set')
    with op.batch_alter_table('calculation_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calculation_run_upload_timestamp'))
        batch_op.drop_index(batch_op.f('ix_calculation_run_report_period'))

    op.drop_table('calculation_run')
    with op.batch_alter_table('app_setting', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_setting_key'))

    op.drop_table('app_setting')
    # ### end Alembic commands ###
