"""Add total_potential_bonus to PersonResult

Revision ID: 154db97ef73d
Revises: 7853c37e5830
Create Date: 2026-01-31 22:04:36.121461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '154db97ef73d'
down_revision = '7853c37e5830'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_potential_bonus', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person_result', schema=None) as batch_op:
        batch_op.drop_column('total_potential_bonus')

    # ### end Alembic commands ###
