"""empty message

Revision ID: d6d3211aeb5c
Revises: 7853c37e5830
Create Date: 2026-02-07 23:39:42.845708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6d3211aeb5c'
down_revision = '7853c37e5830'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_declared', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_base', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_acceptable', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('commission_base', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('commission_acceptable', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('commission_collected', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('bonus_base', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('bonus_acceptable', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('bonus_collected', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('payable_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('remaining_acceptable', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('remaining_base', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person_result', schema=None) as batch_op:
        batch_op.drop_column('remaining_base')
        batch_op.drop_column('remaining_acceptable')
        batch_op.drop_column('payable_amount')
        batch_op.drop_column('bonus_collected')
        batch_op.drop_column('bonus_acceptable')
        batch_op.drop_column('bonus_base')
        batch_op.drop_column('commission_collected')
        batch_op.drop_column('commission_acceptable')
        batch_op.drop_column('commission_base')
        batch_op.drop_column('total_acceptable')
        batch_op.drop_column('total_base')
        batch_op.drop_column('total_declared')

    # ### end Alembic commands ###
